php:
  preset: laravel
  enabled:
    - long_list_syntax
  disabled:
    - concat_without_spaces
    - not_operator_with_successor_space
    - cast_spaces
    - trailing_comma_in_multiline_array
    - heredoc_to_nowdoc
    - phpdoc_summary
    - short_list_syntax
  risky: false
